# ? Peticiones de API/USERS


GET http://localhost:3000/api/users/

###

POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "name": "Rocío",
  "surname": "Corrales",
  "city": "Cádiz",
  "email": "Rocio@sprencia.com",
  "password": "rocio23!34J"
}

### 

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "Jose@sprencia.com",
  "password": "jose23!34J"
}

###

# ? Peticiones de API/CATALOG

GET http://localhost:3000/api/catalog/


### 
POST http://localhost:3000/api/catalog/new
Content-Type: application/json

{
  "image": "https://images.pexels.com/photos/4056723/pexels-photo-4056723.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  "description": "Clases de Yoga para la tercera edad, especializados en estiramientos articulares, relajación mental y conservación física. Además disponemos de un descuento del 20% para los primeros 10 alumnos. Disponemos de clases unicamente para mujeres.",
  "summary": "Clases de Yoga para la tercera edad.",
  "schedule": "M, X, F", 
  "price": "19"
}

# ? Peticiones de API/comment
###

POST http://localhost:3000/api/comment/new
Content-Type: application/json

{
  "user_id": "5",
  "activity_id": "1",
  "description": "Unas clases magníficas.",
  "date": "2023-03-02"
}
